export const keywords = {
    GRAND_LIVRE_COMPTES: [
      "grand",
      "livre",
      "livres",
      "compte",
      "comptes",
      "gl",
      "glcompte",
      "glcomptes",
      "grandlivre",
      "grandlivrecompte",
      "grandlivrecomptes",
    ],
    GRAND_LIVRE_TIERS: [
      "grand",
      "livre",
      "livres",
      "tiers",
      "tier",
      "gl",
      "gltiers",
      "gltier",
      "grandlivretiers",
      "grandlivretier",
    ],
    PLAN_COMPTES: [
      "plan",
      "compte",
      "comptes",
      "cmpt",
      "pl",
      "plcompte",
      "plcomptes",
      "plancompte",
      "plancomptes",
    ],
    PLAN_TIERS: [
      "plan",
      "tiers",
      "tier",
      "trs",
      "pl",
      "pltiers",
      "pltier",
      "plantiers",
      "plantier",
    ],
    CODE_JOURNAL: [
      "code",
      "journal",
      "journaux",
      "journeau",
      "cd",
      "cj",
      "codejournal",
      "codejournaux",
      "cdjournal",
    ],
  };